export const DEFAULT_ICON = "􀛧";

export const APP_ICONS: Record<string, string> = {
  iTerm2: "􀩼",
  Terminal: "􀩼",
  Warp: "􀩼",
  Xcode: "􀤯",
  "Visual Studio Code": "􀤙",
  Code: "􀤙",
  Cursor: "􀤙",
  "SF Symbols": "􁂮",
  Firefox: "􀎬",
  "Firefox Developer Edition": "􀎬",
  Arc: "􀎬",
  Safari: "􀎬",
  "Google Chrome": "􀎬",
  "Brave Browser": "􀎬",
  "Microsoft Edge": "􀎬",
  "Zen Browser": "􀎬",
  Simulator: "􀟜",
  "App Store": "􀈄",
  Notion: "􀺴",
  Obsidian: "􀺴",
  Notes: "􀓕",
  "1Password": "􀙵",
  Messages: "􀌤",
  Messenger: "􀌤",
  Telegram: "􀌤",
  WhatsApp: "􀌤",
  Signal: "􀌤",
  Mail: "􀍕",
  Polymail: "􀍕",
  Spark: "􀍕",
  Mimestream: "􀍕",
  Superhuman: "􀍕",
  Calendar: "􀉉",
  Cron: "􀉉",
  Fantastical: "􀉉",
  "Notion Calendar": "􀉉",
  "zoom.us": "􀍉",
  FaceTime: "􀍉",
  Asana: "􀷾",
  Linear: "􀷾",
  Slack: "􀃪",
  Discord: "􀃪",
  "Microsoft Teams": "􀃪",
  "System Settings": "􀣋",
  "System Preferences": "􀣋",
  Postman: "􀪹",
  Insomnia: "􀪹",
  RapidAPI: "􀪹",
  Finder: "􀈕",
  Spotify: "􀑪",
  "Apple Music": "􀑪",
  Music: "􀑪",
  Preview: "􀏅",
  Photos: "􀏅",
  Figma: "􀎸",
  Docker: "􀐛",
  "Docker Desktop": "􀐛",
  OrbStack: "􀐛",
  TablePlus: "􀤃",
  Postico: "􀤃",
  "pgAdmin 4": "􀤃",
  DataGrip: "􀤃",
  "Activity Monitor": "􀍟",
  Claude: "􀋃",
  ChatGPT: "􀫥",
  Raycast: "􀊫",
  Alfred: "􀊫",
  Bear: "􀣠",
  Things: "􀆅",
  Reminders: "􀆅",
  Todoist: "􀆅",
  TickTick: "􀆅",
  "Keychain Access": "􀟖",
  "Install Command Line Developer Tools": "􀤙",
  Maps: "􀙊",
  Podcasts: "􀺺",
};
